import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme.provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Providers wrao around our application and give them access to global state / data.
// We can also use this to wrap our application with a theme provider.
// NextThemesProvider - Give our application access to light / dark mode data.
// Swithch from light mode to dark mode <-- user interaction // needs the client to exist.


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme='dark'>
          <main className="flex min-h-screen flex-col items-center p-24">
            <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
              <h2 className='text-2xl text-bold'>Pokemon Finder</h2>
            </div>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
